spring:
  application:
    name: SerpentiaApplication
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000   # Cierra conexiones inactivas después de 30s
      max-lifetime: 1800000  # 30 min (menor que el timeout de PostgreSQL)
      keepalive-time: 300000
  jpa:
    hibernate:
      ddl-auto: update

# Configuración de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: Serpentia API
    description: API para el juego multijugador Serpentia
    version: 1.0.0
    contact:
      name: Equipo Serpentia
      email: support@serpentia.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT