spring:
  application:
    name: SerpentiaApplication
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}

    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000   # Cierra conexiones inactivas después de 30s
      max-lifetime: 1800000  # 30 min (menor que el timeout de PostgreSQL)
      keepalive-time: 300000

  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_ADDR}
      port: 6380
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: 0
      ssl:
        enabled: true
    cache:
      type: redis

